#!/bin/bash

ROSLISP_REPL_DIR=$(dirname $0)

if ! [ -d ${ROSLISP_REPL_DIR}/slime ]; then
    echo "You need to call 'rosmake roslisp_repl' first."
    exit 1
fi

[ -f ${HOME}/.swank.lisp ] || cp ${ROSLISP_REPL_DIR}/swank.lisp ${HOME}/.swank.lisp
emacs -q -L ${ROSLISP_REPL_DIR} --eval "(require 'repl-config)"
