#!/bin/sh -e
# /usr/lib/emacsen-common/packages/remove/rosemacs-el

FLAVOR=$1
PACKAGE=rosemacs-el

if test "${FLAVOR}" = 'emacs' -o "$(echo ${FLAVOR} | cut -c-6)" = 'xemacs'; then
    exit 0
fi

echo "remove/${PACKAGE}: purging byte-compiled files for ${FLAVOR}"
rm -rf "/usr/share/${FLAVOR}/site-lisp/${PACKAGE}"
