#!/usr/bin/env sh

SLIME_ROS_DIR=$(rospack find slime_ros)
${SLIME_ROS_DIR}/slime_ros_init

ROSLISP_REPL_DIR=$(rospack find roslisp_repl)
emacs -q -L ${ROSLISP_REPL_DIR} -L ${SLIME_ROS_DIR} --eval "(require 'repl-config)"
